version: '3.7'

services:
  mysql:
    image: mysql:5.7.16
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    privileged: true
    environment:
      MYSQL_ROOT_PASSWORD: gcnote
      MYSQL_USER: gcnote
      MYSQL_PASSWORD: gcnote
      MYSQL_DATABASE: gcnote
    container_name: gcnote_db_1
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql_data:/var/lib/mysql

  golang:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    ports:
      - "8080:8080"
    container_name: gcnote_web_1
    links:
      - mysql
    volumes:
      - ./src:/go/src/github.com/lindamanf/gcnote
